### ISSUE TITLE
잠깐 코드보고 피드백드립니당

### ISSUE THREAD

**Issue by pksung1** [365kim/web_study#1]
https://codepen.io/365kim/pen/yLONJaz

역시 열심히 해주셔서 너무 감사합니다 ㅠㅠ

간단하게 사이트 보고 피드백 드립니다~

- [x] 좌측 프로필 이미지가 .container 를 벗어나서 .sticky 영역을 침범하고 있습니다.

일부러 그렇게 스타일링을 하셨다면 맞지만 혹시 벗어난거라면 이미지에 width: 100%를 줘서 .left 가로길이에 맞추거나 .sticky영역에 z-index: 1000 정도? 주시면 .sticky영역에 이미지가 침범하지 않습니다!

- [ ] .container클래스를 중간과 하단 두개를 사용하고있습니다.

하단은 명칭에 맞게 footer, 중단은 container보단 content? main? 이런 정확한 명칭이 좋지 않을까.. 합니다! container는 div같은 공간의 묶음이라 표현하는것 같아서..
HTML5인 시멘틱태그로 명칭을 확실하게 해주시면  더욱 보기좋은 코드가 될것같습니다!
```html
<div id="footer" class="container"> ... </div>
<div id="footer"><div class="container>...</div></div>
<footer class="container">...</div>
```

html5 시멘틱태그 => https://snusang.tistory.com/4

- [ ] .right 클래스 안에 div공간을 이렇게 나누는건 어떨까요?

각 section마다 아래와 같이 구분하면 반응형 작업을 할때도 공간구분이 되어있어 좀더 쉬운것 같습니다. 
(이건 개인 퍼블리싱 하는것에 다른것같습니다 ㅎㅎ.. )
```html
<div id="pinned" />...</div>
<div id="contribution-in-last-year">...</div>
<div id="contribution-activity">...</div>
또는
<section id="pinned" />...</section>
<section id="contribution-in-last-year">...</section>
<section id="contribution-activity">...</section>
```

정말 열심히 해주셔서 너무 감사합니다 ㅠㅠ
시간날때 열심히 피드백 해드리겠습니다!

모르시는것 있으면 따로 디코에 말씀하셔두 됩니다! 같이 화면보면서 공부해도 되요!!
감사합니다~

**Comment by 365kim** [comment]
성원님! 
우선 바쁘신데도 시간내서 피드백 주셔서 정말정말 감사합니다! 
꼼꼼하게 체크해주셔서 또 감사드리구요~!~! 👍 👍 

#### 1. 프로필 이미지의 위치
![image](https://user-images.githubusercontent.com/60066472/91045320-ae588e00-e651-11ea-85d7-230483ca4cf8.png)
제가 제대로 이해했다면 이 부분 말씀해주시는것 같습니다
정말 아닐 것 같지만 의도한게 맞답니당 ㅜ_ㅜ
저도 이부분이 왜 이렇게 되어있는지 잘모르겠지만... 어쨌든 실제와 비슷하게 구현하는게 목표라고 생각해서 디코 수업시간 때 배웠던 position으로 위치를 위로 넘어가게 해봤습니당!
```
.entity img {
  position: relative;
  top: -25px;
  ...
}
```

#### 2. HTML 시맨틱 태그
스터디에 조금 늦게 들어오면서 앞에 w3school의 html 문서는 사실 하나도 못봤는데 이게 이렇게 들통이 났네용 ㅎㅎ
이참에 공부할 좋은 기회가 된 것 같아요! 참고할 좋은 소스까지 챙겨주셔서 정말정말 감사합니당
말씀해주신 내용 참고해서 적절한 태그가 될 수 있도록 잘 반영해보도록 하겠습니다.

#### 본문 중 h2태그 구분
오 작성해주신대로 구분하는게 문서의 흐름이 훨씬 눈에 잘들어오는 것 같습니다. 저거 보고 제거 다시 보니까 도대체 왜이렇게했지? 싶네요ㅋㅋㅋㅋ 섹션으로 하고 id도 주면 말씀해주신대로 미디어쿼리 쓸 때도 안헷갈리고 훨씬 편할 것 같아요! 반영해서 보완하겠습니당

더딘 학습자인데 항상 격려말씀해주셔서 감사합니다ㅎㅎ
감사합니다 :)

**Comment by pksung1** [comment]
와 깃헙이 저렇게 되있었군요 ㅋㅋㅋㅋ 처음알았습니다..
구조도 잘 만들어놓으셔서 피드백은 응원밖에 할게없네요 ㅋㅋㅋㅋ 파이팅입니다!

**Comment by 365kim** [comment]
감사합니다!!! 💪💪💪
